version: '3.9'

networks:
  asp-testing:
    driver: bridge
services:
  app:
    container_name: asp-net-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - asp-testing
    depends_on:
      - db
    
  db:
    container_name: postgres_test
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cars
    volumes:
      - ./postgresql:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - asp-testing
volumes:
  postgresql: